#!/usr/bin/env python3
"""
Applies Russian translations on top of the ru/ pages generated by
build-i18n.py (which only copies structure/paths, not text).

Run AFTER build.js and build-i18n.py, every time either runs, so
translations don't get wiped by the next rebuild:

    node build.js && rm -rf ru && python3 build-i18n.py && python3 translate-ru.py

Translations are plain (source_substring -> russian_substring) pairs per
file. Keep pairs specific enough to be unambiguous; order matters when one
pair's target text could be a substring of another's source.
"""

from pathlib import Path

ROOT = Path(__file__).parent
RU = ROOT / "ru"

# ---------------------------------------------------------------------------
# Shared nav / chrome strings — applied to every RU page.
# ---------------------------------------------------------------------------
COMMON = [
    ('<a href="/" class="" >Home</a>', '<a href="/" class="" >Главная</a>'),
    ('<li><a href="/" class="active">Home</a></li>', '<li><a href="/" class="active">Главная</a></li>'),
    ('<li><a href="/" class="">Home</a></li>', '<li><a href="/" class="">Главная</a></li>'),
    ('>Home<', '>Главная<'),
    ('>Projects<', '>Проекты<'),
    ('>CV<', '>Резюме<'),
    ('>Get in Touch<', '>Связаться<'),
    ('>Discuss a Similar Project<', '>Обсудить похожий проект<'),
    ('>View project<', '>Смотреть проект<'),
    ('>View All Projects<', '>Все проекты<'),
    ('>Previous Project<', '>Предыдущий проект<'),
    ('>Next Project<', '>Следующий проект<'),
    ('>Download CV<', '>Скачать резюме<'),
    ('placeholder="Search projects...">', 'placeholder="Поиск по проектам...">'),
    ('>All tools<', '>Все инструменты<'),
    ('id="filterAll" class="filter-checkbox" data-tool="all" checked>\n              <label for="filterAll" class="filter-label">All</label>',
     'id="filterAll" class="filter-checkbox" data-tool="all" checked>\n              <label for="filterAll" class="filter-label">Все</label>'),
    ('© 2026 Victoria Fine. All rights reserved.', '© 2026 Виктория Файн. Все права защищены.'),
    ('Hi%20Victoria!%20I%20visited%20your%20website%20and%20would%20like%20to%20discuss%20a%20project.',
     '%D0%97%D0%B4%D1%80%D0%B0%D0%B2%D1%81%D1%82%D0%B2%D1%83%D0%B9%D1%82%D0%B5%2C%20%D0%92%D0%B8%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D1%8F!%20%D0%AF%20%D0%B7%D0%B0%D1%88%D0%B5%D0%BB%20%D0%BD%D0%B0%20%D0%B2%D0%B0%D1%88%20%D1%81%D0%B0%D0%B9%D1%82%20%D0%B8%20%D1%85%D0%BE%D1%82%D0%B5%D0%BB%20%D0%B1%D1%8B%20%D0%BE%D0%B1%D1%81%D1%83%D0%B4%D0%B8%D1%82%D1%8C%20%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82.'),
]

# ---------------------------------------------------------------------------
# Per-page translations.
# ---------------------------------------------------------------------------
PAGES = {

"index.html": [
    ("<h1>Systems Architect & Builder<br>for E-commerce Operations</h1>",
     "<h1>Архитектор и интегратор систем<br>для e-commerce</h1>"),
    ('<p class="hero-subtitle">System design, storefront deployment, and operational integration.</p>',
     '<p class="hero-subtitle">Проектирование систем, запуск интернет-магазинов и интеграция операционных процессов.</p>'),
    (">Book a Discovery Call<", ">Запланировать звонок<"),
    (">View My Projects<", ">Смотреть проекты<"),
    ('<p class="hero-lang-note">Available in English and Russian</p>',
     '<p class="hero-lang-note">Работаю на английском и русском языках</p>'),
    ("<h2>Hey!</h2>", "<h2>Привет!</h2>"),
    ("<p>Hey, I'm Victoria — 15+ years in e-commerce and business automation. Based in Israel, I work in English and Russian.</p>",
     "<p>Привет, я Виктория — больше 15 лет в e-commerce и автоматизации бизнеса. Живу в Израиле, работаю на английском и русском.</p>"),
    ("<p>I started in digital marketing and worked my way up to running sales, marketing, supply, fulfillment, warehouse, and finance — the whole operational side of a business, not just one piece of it.</p>",
     "<p>Начинала с цифрового маркетинга и прошла путь до управления продажами, маркетингом, закупками, фулфилментом, складом и финансами — всей операционной частью бизнеса, а не отдельным её куском.</p>"),
    ("<p>That's usually what gets missed when someone hires a Shopify developer. The store launches fine, but three months later the inventory doesn't match across channels, orders are still tracked in a spreadsheet, and nobody fully trusts the numbers. Nobody thought to plan for that at the start.</p>",
     "<p>Именно это чаще всего упускают, когда нанимают разработчика на Shopify. Магазин запускается нормально, но через три месяца остатки не сходятся между каналами, заказы всё ещё ведутся в таблице, а цифрам никто до конца не доверяет. Об этом просто не подумали на старте.</p>"),
    ("<p>I build for that from the beginning — the systems and automation that keep the business running once the store is live, not just the store itself.</p>",
     "<p>Я закладываю это с самого начала — системы и автоматизацию, которые держат бизнес на ходу после запуска магазина, а не только сам магазин.</p>"),
    ("<p>Happy to help with anything that speeds up your e-commerce.</p>",
     "<p>Буду рада помочь с тем, что ускорит ваш e-commerce.</p>"),
    ('alt="From chaos to structured systems"', 'alt="От хаоса к структурированным системам"'),
    ("<h2>Core Expertise</h2>", "<h2>Основная экспертиза</h2>"),
    ('<p class="section-subtitle">Transforming fragmented workflows into intentional, scalable systems — from data foundations to storefront architecture and automation.</p>',
     '<p class="section-subtitle">Превращаю разрозненные процессы в продуманные, масштабируемые системы — от основ данных до архитектуры магазина и автоматизации.</p>'),
    ("<h3>Operational Systems</h3>", "<h3>Операционные системы</h3>"),
    ('<p class="card-subtitle-text">From spreadsheets to a single source of truth.</p>',
     '<p class="card-subtitle-text">От таблиц к единому источнику данных.</p>'),
    ('<p class="card-description">Design and deployment of custom databases and ERP/PIM solutions. Moving businesses from fragmented spreadsheets into a single source of truth for inventory, order management, and unit economics.</p>',
     '<p class="card-description">Проектирование и внедрение баз данных и ERP/PIM-решений под задачу. Перевожу бизнес с разрозненных таблиц на единый источник данных для склада, заказов и юнит-экономики.</p>'),
    ("<h3>Workflow Automation</h3>", "<h3>Автоматизация процессов</h3>"),
    ('<p class="card-subtitle-text">Make your software stack communicate.</p>',
     '<p class="card-subtitle-text">Чтобы все инструменты общались между собой.</p>'),
    ('<p class="card-description">Eliminating manual data entry by connecting storefronts, warehouses, CRM, and payment gateways. I build seamless integrations that reduce errors and free up time for strategy.</p>',
     '<p class="card-description">Убираю ручной ввод данных, связывая магазин, склад, CRM и платёжные системы. Строю интеграции, которые снижают количество ошибок и освобождают время для стратегии.</p>'),
    ("<h3>Storefront Architecture</h3>", "<h3>Архитектура интернет-магазина</h3>"),
    ('<p class="card-subtitle-text">Scalable e-commerce foundations.</p>',
     '<p class="card-subtitle-text">Масштабируемая основа для e-commerce.</p>'),
    ('<p class="card-description">End-to-end development of scalable e-commerce platforms. From UI/UX prototyping to fully functional architectures, including B2B wholesale portals and multi-currency setups.</p>',
     '<p class="card-description">Полный цикл разработки масштабируемых e-commerce платформ. От UI/UX-прототипов до полностью рабочей архитектуры, включая B2B-порталы и мультивалютные настройки.</p>'),
    ('<p class="card-tools-label">Tools</p>', '<p class="card-tools-label">Инструменты</p>'),
    ("<h2>My Projects</h2>", "<h2>Мои проекты</h2>"),
    ('<p class="section-subtitle">A selection of recent projects I\'ve worked on.</p>',
     '<p class="section-subtitle">Подборка последних проектов, над которыми я работала.</p>'),
    ("<h2>Want to learn more about my experience?</h2>", "<h2>Хотите узнать больше о моём опыте?</h2>"),
    ("<p>Check out my resume page or download a copy for a full overview of my skills and past roles.</p>",
     "<p>Загляните на страницу резюме или скачайте копию — там полный обзор навыков и опыта работы.</p>"),
    (">View Resume<", ">Резюме<"),
],

"contact.html": [
    ("<h1>Get in Touch</h1>", "<h1>Связаться</h1>"),
    ("<p class=\"contact-subtitle\">Have a project in mind or want to discuss a role? I'd love to hear from you.</p>",
     "<p class=\"contact-subtitle\">Есть проект на примете или хотите обсудить сотрудничество? Буду рада вас услышать.</p>"),
    ('<h2 style="font-size:24px; margin-bottom:24px;">Contact channels</h2>',
     '<h2 style="font-size:24px; margin-bottom:24px;">Каналы связи</h2>'),
    ('<span class="contact-link-label">Upwork Profile</span>',
     '<span class="contact-link-label">Профиль на Upwork</span>'),
    ('<h2 style="font-size:24px; margin-bottom:24px;">Send a message</h2>',
     '<h2 style="font-size:24px; margin-bottom:24px;">Написать сообщение</h2>'),
    ('color:#666;">Name</label>', 'color:#666;">Имя</label>'),
    ('placeholder="Your name"', 'placeholder="Ваше имя"'),
    ('color:#666;">Email</label>', 'color:#666;">Email</label>'),
    ('color:#666;">Message</label>', 'color:#666;">Сообщение</label>'),
    ('placeholder="Tell me about your project or role..."', 'placeholder="Расскажите о проекте или роли..."'),
    ('>Send Message<', '>Отправить<'),
],

}


def apply_translations(html: str, pairs) -> str:
    for old, new in pairs:
        if old not in html:
            print(f"    (not found, skipped) {old[:60]}")
            continue
        html = html.replace(old, new)
    return html


PROJECT_CARD_TRANSLATIONS = {
    "artline-craft-storefront": {
        "title": "Пересборка магазина для бренда handmade-товаров",
        "tagline": "Собрала разрозненный магазин на Shopify (следы нескольких агентств) в самостоятельный магазин с продуманной архитектурой каталога",
        "companyLocation": "Румыния",
    },
    "fullflat-operations": {
        "title": "Система управления заказами для интернет-магазина мебели",
        "tagline": "Полный цикл заказа — от запроса до подтверждения доставки и автоматических отзывов",
        "companyLocation": "ОАЭ",
    },
    "fullflat-finance": {
        "title": "Финансовые операции и система P&L",
        "tagline": "30+ статей бюджета с полностью автоматизированным P&L, Cash Flow и отчётностью план/факт",
        "companyLocation": "ОАЭ",
    },
    "fullflat-taxonomy-reviews": {
        "title": "AI-агенты для таксономии и отзывов о товарах",
        "tagline": "Автоматизировала обработку новых товаров и фото доставки в готовый контент по стандарту PIM — классификация и отзывы клиентов без ручной работы на каждом шаге",
        "companyLocation": "ОАЭ",
    },
    "artline-b2b-portal": {
        "title": "B2B-портал для оптовых продаж",
        "tagline": "Self-serve B2B-портал для европейских бизнес-покупателей: льготные цены без НДС, верификация через VIES и автоматический мультиязычный инвойсинг",
        "companyLocation": "Румыния",
    },
    "artline-email-automation": {
        "title": "Миграция и автоматизация email-маркетинга",
        "tagline": "Перенесла email-маркетинг Artline с встроенной почты Shopify на Klaviyo, пересобрала автоматические цепочки на более функциональной платформе",
        "companyLocation": "Румыния",
    },
    "fullflat-pim": {
        "title": "Система управления товарными данными (PIM)",
        "tagline": "Двуязычный каталог мебели с ценообразованием от нескольких поставщиков и AI-генерацией интерьерных изображений",
        "companyLocation": "ОАЭ",
    },
    "fullflat-oms-agent": {
        "title": "AI-агент для системы управления заказами",
        "tagline": "Автоматизировала создание визуализаций заказа для клиента — с реальными образцами материалов из каталога, чтобы показать точно то, что клиент купил, ещё до доставки",
        "companyLocation": "ОАЭ",
    },
}


def translate_projects_json():
    import json
    pj = RU / "projects.json"
    if not pj.exists():
        return
    data = json.loads(pj.read_text(encoding="utf-8"))
    for p in data:
        t = PROJECT_CARD_TRANSLATIONS.get(p.get("id"))
        if t:
            p["title"] = t["title"]
            p["tagline"] = t["tagline"]
            p["companyLocation"] = t["companyLocation"]
    pj.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    print("translated: ru/projects.json (card previews)")


def main():
    for rel_page, pairs in PAGES.items():
        if rel_page == "index.html":
            path = RU / "index.html"
        elif rel_page in ("contact.html",):
            path = RU / rel_page.replace(".html", "") / "index.html"
        else:
            path = RU / rel_page

        if not path.exists():
            print(f"skip (not found): {path}")
            continue

        html = path.read_text(encoding="utf-8")
        html = apply_translations(html, COMMON)
        html = apply_translations(html, pairs)
        path.write_text(html, encoding="utf-8")
        print(f"translated: {path.relative_to(ROOT)}")

    # Apply COMMON-only translations to every other ru page that isn't
    # explicitly listed above yet (nav chrome, buttons, footer, etc.)
    for html_file in RU.rglob("index.html"):
        rel = html_file.relative_to(RU)
        already_done = {
            "index.html",
            "contact/index.html",
        }
        if str(rel) in already_done:
            continue
        html = html_file.read_text(encoding="utf-8")
        html = apply_translations(html, COMMON)
        html_file.write_text(html, encoding="utf-8")
        print(f"chrome-only translated: {html_file.relative_to(ROOT)}")

    ru_404 = RU / "404.html"
    if ru_404.exists():
        html = ru_404.read_text(encoding="utf-8")
        html = apply_translations(html, COMMON)
        ru_404.write_text(html, encoding="utf-8")
        print("chrome-only translated: ru/404.html")

    translate_projects_json()


if __name__ == "__main__":
    main()
